# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer/fdldialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 600)
        self.fdldialog = QtWidgets.QWidget(MainWindow)
        self.fdldialog.setObjectName("fdldialog")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fdldialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.fdldialog)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.fdldialog)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 23))
        self.menubar.setObjectName("menubar")
        self.mTaskMenu = QtWidgets.QMenu(self.menubar)
        self.mTaskMenu.setObjectName("mTaskMenu")
        self.mFileMenu = QtWidgets.QMenu(self.menubar)
        self.mFileMenu.setObjectName("mFileMenu")
        self.mDownloadMenu = QtWidgets.QMenu(self.menubar)
        self.mDownloadMenu.setObjectName("mDownloadMenu")
        self.mHelpMenu = QtWidgets.QMenu(self.menubar)
        self.mHelpMenu.setObjectName("mHelpMenu")
        self.mSettingMenu = QtWidgets.QMenu(self.menubar)
        self.mSettingMenu.setObjectName("mSettingMenu")
        self.menuUI_Language = QtWidgets.QMenu(self.mSettingMenu)
        self.menuUI_Language.setObjectName("menuUI_Language")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setWindowTitle("toolBar")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.mAddNewTaskAction = QtWidgets.QAction(MainWindow)
        self.mAddNewTaskAction.setShortcut("Ctrl+N")
        self.mAddNewTaskAction.setObjectName("mAddNewTaskAction")
        self.mExitAction = QtWidgets.QAction(MainWindow)
        self.mExitAction.setShortcut("Ctrl+Q")
        self.mExitAction.setObjectName("mExitAction")
        self.mStopDownloadAction = QtWidgets.QAction(MainWindow)
        self.mStopDownloadAction.setObjectName("mStopDownloadAction")
        self.mOptionalAction = QtWidgets.QAction(MainWindow)
        self.mOptionalAction.setObjectName("mOptionalAction")
        self.mAboutAction = QtWidgets.QAction(MainWindow)
        self.mAboutAction.setObjectName("mAboutAction")
        self.mUpdateAction = QtWidgets.QAction(MainWindow)
        self.mUpdateAction.setObjectName("mUpdateAction")
        self.mEnglishAction = QtWidgets.QAction(MainWindow)
        self.mEnglishAction.setText("English")
        self.mEnglishAction.setObjectName("mEnglishAction")
        self.mChineseAction = QtWidgets.QAction(MainWindow)
        self.mChineseAction.setText("中文简体")
        self.mChineseAction.setObjectName("mChineseAction")
        self.mTaskMenu.addAction(self.mAddNewTaskAction)
        self.mTaskMenu.addAction(self.mExitAction)
        self.mFileMenu.addAction(self.mStopDownloadAction)
        self.mDownloadMenu.addAction(self.mOptionalAction)
        self.mHelpMenu.addAction(self.mAboutAction)
        self.mHelpMenu.addAction(self.mUpdateAction)
        self.menuUI_Language.addAction(self.mEnglishAction)
        self.menuUI_Language.addAction(self.mChineseAction)
        self.mSettingMenu.addAction(self.menuUI_Language.menuAction())
        self.menubar.addAction(self.mTaskMenu.menuAction())
        self.menubar.addAction(self.mFileMenu.menuAction())
        self.menubar.addAction(self.mDownloadMenu.menuAction())
        self.menubar.addAction(self.mSettingMenu.menuAction())
        self.menubar.addAction(self.mHelpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FDL - PyQt5 Downloader"))
        self.mTaskMenu.setTitle(_translate("MainWindow", "Task"))
        self.mFileMenu.setTitle(_translate("MainWindow", "File"))
        self.mDownloadMenu.setTitle(_translate("MainWindow", "Download"))
        self.mHelpMenu.setTitle(_translate("MainWindow", "Help"))
        self.mSettingMenu.setTitle(_translate("MainWindow", "Settings"))
        self.menuUI_Language.setTitle(_translate("MainWindow", "UI Language"))
        self.mAddNewTaskAction.setText(_translate("MainWindow", "Add New Task(N)"))
        self.mAddNewTaskAction.setToolTip(_translate("MainWindow", "add new task"))
        self.mExitAction.setText(_translate("MainWindow", "Exit"))
        self.mExitAction.setToolTip(_translate("MainWindow", "exit"))
        self.mStopDownloadAction.setText(_translate("MainWindow", "Stop Download"))
        self.mStopDownloadAction.setToolTip(_translate("MainWindow", "stop download"))
        self.mOptionalAction.setText(_translate("MainWindow", "Optional"))
        self.mOptionalAction.setToolTip(_translate("MainWindow", "optional"))
        self.mAboutAction.setText(_translate("MainWindow", "About"))
        self.mAboutAction.setToolTip(_translate("MainWindow", "about"))
        self.mUpdateAction.setText(_translate("MainWindow", "Update"))
        self.mUpdateAction.setToolTip(_translate("MainWindow", "update"))

